#!/bin/bash

check_package() {
  package=$1

  if ! command -v "$package" &>/dev/null; then
    echo "You need to install $package."
    echo "If you are using a Debian-based system like Ubuntu, use sudo apt install $package."
    exit
  fi
}

check_package toilet
check_package fzf

cmd=$(f=$(ls /usr/share/figlet/ | sed '/-/d' | sed 's/\..*$//g') && for i in ${f[@]}; do echo $i; done)
selected_font=$(echo $cmd | tr ' ' '\n' | fzf)

read -p "Text: " text
toilet -f $selected_font $text
